---
- name: update web servers
  hosts: _Jenkins_Ansible
  remote_user: ubuntu
  #ansible_ssh_user: ubuntu, not valid for playbooks

  vars_files:
    - /etc/ansible/vars/info.yml

  tasks:
    - name: Pinging
      ping:

    - name: ensure wireshark is at the latest version
      apt:
        name: wireshark
        state: latest

- name: update db servers
  hosts: _NFS
  remote_user: ec2-user
  #ansible_ssh_user: ec2-user 

  vars_files:
    - /etc/ansible/vars/info.yml

  tasks:
    - name: Pinging
      ping:
    - name: ensure wireshark is at the latest version
      yum:
        name: wireshark
        state: latest
