- hosts: lb
  include: ../dynamic-assignments/env-vars.yml
  roles:
    - { role: apache, when: enable_apache_lb and load_balancer_is_required }
    #- { role: nginx, when: enable_nginx_lb and load_balancer_is_required }

