---
#- hosts: all
#- import_playbook: ../static-assignments/common.yml

#- hosts: all
#- import_playbook: ../static-assignments/common-del.yml

- hosts: uat-webservers #_uat_web
- import_playbook: ../static-assignments/uat-webservers.yml

- hosts: lb
- import_playbook: ../static-assignments/loadbalancers.yml

#- name: Loadbalancers assignment
#  hosts: lb
#  import_playbook: ../static-assignments/loadbalancers.yml
#  when: load_balancer_is_required 

